### PR TITLE
header file for the printf project

### LINKED ISSUE #4: Create a header file
Create a header file (.h) :
-It have to be guarded with the #ifndef, #define and end with #endif
-it must contain all the projects prototypes 
-it must comply the Betty style and documentation

### PR DESCRIPTION
**Pull request by Avellin003**
closes #4

### CODE REVIEW

**Comment by Okibe00** [comment]
change the file name from header.h to main.h

**Comment by Okibe00** [comment]
## Link the pull request to the issue it addresses
This can be done by adding `close #issue_number` to the pull request description
Example
close #issue_number 
[click for more detail](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

**Comment by Avellin003** [comment]
close #4

**Comment by Okibe00** [comment]
closes #4

**Comment by Avellin003** [comment]
closes #4

**Comment by Avellin003** [comment]
fixes #4

**Comment by Avellin003** [comment]
closes #12,closes #4

**Pull request merged**
